### PR TITLE
Additional Features for Markers

### PR DESCRIPTION
**Pull request by andyphillips404**
Updates include:
1.  Allowing to set marker Z index
2.  Allowing to set a google map icon, which allows custom setting of the image of the marker
3.  Fixed issue with GoogleMapMarker and compare fields of other goodle map marker is null

### CODE REVIEW

**Comment by tjkaal** [comment]
My plan is to create an overlays extension that would manage everything related to the overlays. Just FYI, I haven't forgotten about this, it's just that I don't want to add any more features to the original add-on, it's too bloated already.

**Comment by andyphillips404** [comment]
Thank you for the note back.  I look forward to the update and thanks for the code!

**Comment by tapioaali** [comment]
I'll take a new look on this for the next version coming soon.

**Comment by thinwire** [comment]
This project is no longer being maintained here. It has moved to [https://github.com/parttio/Google-Maps-for-Vaadin](https://github.com/parttio/Google-Maps-for-Vaadin)

Thanks.

**Pull request closed without merging**
