### PR TITLE
Upgraded to Vaadin 8 and pom cleanup

### PR DESCRIPTION
**Pull request by chrosim**
The only neccesary changes for a Vaadin 8 version, and a little pom cleanup #48

### CODE REVIEW

**Comment by hezamu** [comment]
Hi @chrosim, we forked the repo for further development here: https://github.com/parttio/Google-Maps-for-Vaadin

Please submit your PR there as well.

Thanks!

**Comment by thinwire** [comment]
Thank you, @hezamu!
I'M FREE!

**Comment by hezamu** [comment]
You're welcome @thinwire :)

**Comment by chrosim** [comment]
@hezamu Done :)

**Pull request merged**
